XYdata=read.csv("C:/Users/KIIT/Downloads/XYdata.csv",header=F)
names(XYdata)
head(XYdata)
mod=lm(V2~V1,data=XYdata)
summary(mod)
lm_XY <-lm(formula=V2~V1,data=XYdata)
cat("The R Squared Value for XY = ", summary(lm_XY)$r.squared)
a <- summary(lm_XY)
cat("The theta values for XY =", coef(a)[, "t value"])
plot(mod)
abline(lm_XY$coefficients, col = "blue")
title("Regression Line of XY Dataset")
preds<-data.frame(V1=42.123456)
predict(mod,newdta=preds)
preds<-data.frame(V1=60.654321)
predict(mod,newdata=preds)
getwd()

cars=read.csv("C:/Users/KIIT/Downloads/cars.csv",header=T,sep=",")
class(cars)
names(cars)
head(cars)
modl=lm(CO2~Volume + Weight,data=cars)
summary(modl)
lm_Cars <- lm(modl) 
cat("The R Squared Value for Cars  = ", summary(lm_Cars)$r.squared)
b <- summary(lm_Cars)
cat("The theta values for Cars =", coef(b)[, "t value"])
plot(lm_Cars)
preds<-data.frame(Volume=1550,Weight=992)
predict(modl,newdata=preds)
preds<-data.frame(Volume=1545,Weight=1092)
predict(modl,newdata=preds)
preds<-data.frame(Volume=1650,Weight=992)
predict(modl,newdata=preds)
preds<-data.frame(Volume=1500,Weight=892)
predict(modl,newdata=preds)

